AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  intuitlambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::211896897907:role/intuit-s3tos3'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:*'
      VpcConfig:
        SecurityGroupIds:
          - sg-0e5a4f3b
        SubnetIds:
          - subnet-318d0e6e
          - subnet-fd1d9a9b
          - subnet-3a931e1b
          - subnet-d25b0d9f
          - subnet-7fda104e
          - subnet-4c7e0642
      Layers:
        - 'arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-Pillow:15'
        - 'arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-PyMySQL:4'
  Bucket1:
    Type: 'AWS::S3::Bucket'
